---
- name: install dependencies
  apt: >
    pkg={{ item }}
    update_cache=yes
  with_items:
    - ntp

- name: turn off monlist
  lineinfile: >
    dest=/etc/ntp.conf
    regexp="^disable monitor$"
    line="disable monitor"
  notify: restart ntp
