---
- name: master
  hosts: master
  sudo: yes
  vars_files:
    - vars/{{ env }}.yml
  roles:
    - common
    - designate-src

- name: bind
  hosts: bind
  sudo: yes
  vars_files:
    - vars/{{ env }}.yml
  roles:
    - common
    - bind
