---
- name: master
  hosts: master
  sudo: yes
  vars_files:
    - vars/{{ env }}.yml
  roles:
    - common
    - ntp
    - designate-src

- name: bind
  hosts: bind
  sudo: yes
  vars_files:
    - vars/{{ env }}.yml
  roles:
    - common
    - ntp
    - bind

- name: nsd4
  hosts: nsd4
  sudo: yes
  vars_files:
    - vars/{{ env }}.yml
  roles:
    - common
    - ntp
    - nsd4
