---
- name: install depences
  apt: name={{ item }}
  with_items:
    - bind9

- name: disable AppArmor for bind
  shell: >
    touch /etc/apparmor.d/disable/usr.sbin.named
    creates=/etc/apparmor.d/disable/usr.sbin.named
  notify: reload apparmor

- name: put named.conf.options
  template: >
    src=etc/bind/named.conf.options.j2
    dest=/etc/bind/named.conf.options
  notify: restart bind9

- name: put rndc.key
  template: >
    src=etc/bind/rndc.key.j2
    dest=/etc/bind/rndc.key
  notify: restart bind9
